spring:
  application:
    name: CareerLaunch

  data:
    mongodb:
      uri: mongodb+srv://vedalvi16:2Z4oWRFwrNMvKuue@cluster0.7wcnlva.mongodb.net/
      database: CareerLaunch

app:
  jwt:
    # This MUST be kept secret.
    # Generate a secure 64-byte, Base64-encoded secret.
    secret: bXluYW1laXNqYW1lc2JvbmRiYW5kaWFtYnJpdGlzaHNweWFuZGlsaWtlYmFzZWJhbGxzYW5kcGFzc3dvcmRpc3Bhc3N3b3Jk

    # Token expiration time in milliseconds (86400000 = 24 hours)
    expiration-ms: 86400000